import React, { useState, useEffect } from 'react';
import {
    Book, Code, Link as LinkIcon, Plus, Search, Folder, FolderPlus,
    FileText, Copy, ExternalLink, Trash2, Save, X, Database,
    DownloadCloud, Download, ArrowLeft, ChevronRight, CornerUpLeft, Loader
} from 'lucide-react';
import { collection, addDoc, query, where, onSnapshot, deleteDoc, doc, serverTimestamp, updateDoc } from 'firebase/firestore';
import { db } from "../firebase/config";
import toast from 'react-hot-toast'; // <--- NEW IMPORT

// --- SYSTEM DOCUMENTATION ---
const SYSTEM_MANUAL = `
# 🚀 UNITY CORE v3.3 - OPERATING MANUAL

## 1. DASHBOARD (The Hub)
- **Live Overview:** Shows active projects, pending tasks, and real-time team activity.
- **System Broadcast:** Critical announcements from Team Leads appear here.
- **Smart Clock:** Syncs with your local time for precise logging.

## 2. PROJECT VAULT (Command Center)
- **General:** Manage Project Name, Package Name, and Status (Live/Dev).
- **Release & Store:** - Manage Version History (Auto-logs releases).
  - Store Links & Build Artifacts (APK/AAB).
  - Use the **"Rocket Button"** to deploy a new version.
- **Ad Networks:** - Manage AdMob/Unity Ads IDs in a collapsible list.
  - One-click copy for Ad Unit IDs.
- **Smart Save:** No manual save needed! System auto-saves when you switch tabs or projects.

## 3. ARCHIVES (File Manager)
- **Folders & Organization:** Create unlimited folders (e.g., "Ads", "Controllers").
- **Drag & Drop:** Simply drag a script or doc and drop it into a folder to move it.
- **Snippets:** Save reusable C# scripts (Singleton, Ads Manager, etc.).
- **Docs:** Game Design Docs (GDD), Mechanics, Storylines.
- **Resources:** Links to Assets, Drive folders, or references.

## 4. TASKS (Kanban System)
- **Priority System:** Tag tasks as High, Medium, or Low.
- **Time Tracking:** Logs start and end times for performance review.
- **Workflow:** Drag tasks between To-Do, In Progress, and Done.

## 5. TEAM & CHAT
- **Encrypted Chat:** Secure communication with "Seen By" (Double Tick) status.
- **Roster:** View team members, their roles, and status.
- **Live Status:** See who is online in real-time.

---
*Generated by Unity Core System*
`;

const ArchivesView = ({ user }) => {
    const [activeCategory, setActiveCategory] = useState('snippets');
    const [items, setItems] = useState([]);
    const [currentFolder, setCurrentFolder] = useState('root');
    const [folderPath, setFolderPath] = useState([{ id: 'root', name: 'Home' }]);
    const [searchTerm, setSearchTerm] = useState("");

    // Modals
    const [isAddModalOpen, setIsAddModalOpen] = useState(false);
    const [isFolderModalOpen, setIsFolderModalOpen] = useState(false);

    // Loading States
    const [isCreatingFolder, setIsCreatingFolder] = useState(false);
    const [isSavingFile, setIsSavingFile] = useState(false);

    // Form State
    const [newItem, setNewItem] = useState({ title: '', content: '' });
    const [newFolderName, setNewFolderName] = useState('');

    useEffect(() => {
        if (!user?.teamId) return;

        const q = query(
            collection(db, 'artifacts', 'unity-work-os', 'public', 'data', 'archives'),
            where('teamId', '==', user.teamId),
            where('category', '==', activeCategory)
        );

        const unsubscribe = onSnapshot(q, (snapshot) => {
            const allData = snapshot.docs.map(d => ({ id: d.id, ...d.data() }));
            setItems(allData);
        });

        return () => unsubscribe();
    }, [user.teamId, activeCategory]);

    useEffect(() => {
        setCurrentFolder('root');
        setFolderPath([{ id: 'root', name: 'Home' }]);
    }, [activeCategory]);

    const getItemCount = (folderId) => {
        return items.filter(i => i.parentFolderId === folderId && i.type !== 'folder').length;
    };

    const handleDragStart = (e, itemId) => {
        e.dataTransfer.setData("itemId", itemId);
    };

    const handleDragOver = (e) => {
        e.preventDefault();
    };

    const handleDrop = async (e, targetFolderId) => {
        const itemId = e.dataTransfer.getData("itemId");
        if (!itemId) return;

        if (itemId === targetFolderId) return;

        try {
            await updateDoc(doc(db, 'artifacts', 'unity-work-os', 'public', 'data', 'archives', itemId), {
                parentFolderId: targetFolderId
            });
            logActivity(`moved an item into a folder`, 'ARCHIVE_UPDATE');
        } catch (error) {
            console.error("Error moving item:", error);
        }
    };

    const logActivity = async (text, type) => {
        await addDoc(collection(db, 'artifacts', 'unity-work-os', 'public', 'data', 'activities'), {
            text: `${user.name} ${text}`,
            type: type,
            timestamp: serverTimestamp(),
            teamId: user.teamId,
            meta: { view: 'archives' }
        });
    };

    const handleCreateFolder = async () => {
        if (!newFolderName.trim()) return;

        setIsCreatingFolder(true);
        try {
            await addDoc(collection(db, 'artifacts', 'unity-work-os', 'public', 'data', 'archives'), {
                title: newFolderName,
                type: 'folder',
                parentFolderId: currentFolder,
                category: activeCategory,
                teamId: user.teamId,
                createdBy: user.name,
                createdAt: serverTimestamp()
            });

            logActivity(`created folder "${newFolderName}"`, 'ARCHIVE_FOLDER_CREATED');
            setNewFolderName('');
            setIsFolderModalOpen(false);
            toast.success("Folder created!");
        } catch (error) {
            console.error(error);
            toast.error("Failed to create folder");
        } finally {
            setIsCreatingFolder(false);
        }
    };

    const handleSaveFile = async () => {
        if (!newItem.title || !newItem.content) return toast.error("Title and Content required");

        setIsSavingFile(true);
        try {
            await addDoc(collection(db, 'artifacts', 'unity-work-os', 'public', 'data', 'archives'), {
                ...newItem,
                type: 'file',
                parentFolderId: currentFolder,
                category: activeCategory,
                teamId: user.teamId,
                createdBy: user.name,
                createdAt: serverTimestamp()
            });

            let type = activeCategory === 'snippets' ? 'ARCHIVE_SNIPPET_ADDED' : activeCategory === 'docs' ? 'ARCHIVE_DOC_ADDED' : 'ARCHIVE_LINK_ADDED';
            logActivity(`added "${newItem.title}"`, type);

            setNewItem({ title: '', content: '' });
            setIsAddModalOpen(false);
            toast.success("File saved!");
        } catch (error) {
            console.error(error);
            toast.error("Failed to save file");
        } finally {
            setIsSavingFile(false);
        }
    };

    const handleDelete = async (item) => {
        if (!confirm(`Delete "${item.title}"?`)) return;
        await deleteDoc(doc(db, 'artifacts', 'unity-work-os', 'public', 'data', 'archives', item.id));
        logActivity(`deleted "${item.title}"`, 'ARCHIVE_DELETED');
        toast.success("Deleted successfully");
    };

    const enterFolder = (folder) => {
        setCurrentFolder(folder.id);
        setFolderPath(prev => [...prev, { id: folder.id, name: folder.title }]);
    };

    const navigateBreadcrumb = (index) => {
        const newPath = folderPath.slice(0, index + 1);
        setFolderPath(newPath);
        setCurrentFolder(newPath[newPath.length - 1].id);
    };

    const moveItemUp = async (item) => {
        if (folderPath.length <= 1) return;
        const parentId = folderPath[folderPath.length - 2].id;

        await updateDoc(doc(db, 'artifacts', 'unity-work-os', 'public', 'data', 'archives', item.id), {
            parentFolderId: parentId
        });
        logActivity(`moved "${item.title}" up`, 'ARCHIVE_UPDATE');
        toast.success("Item moved up");
    };

    const copyToClipboard = (text) => {
        navigator.clipboard.writeText(text);
        toast.success("Copied to clipboard!");
    };

    const downloadFile = (title, content, category) => {
        const element = document.createElement("a");
        const file = new Blob([content], { type: 'text/plain' });
        element.href = URL.createObjectURL(file);
        const safeTitle = title.replace(/[^a-z0-9]/gi, '_').toLowerCase();
        const extension = category === 'snippets' ? 'cs' : 'txt';
        element.download = `${safeTitle}.${extension}`;
        document.body.appendChild(element);
        element.click();
        document.body.removeChild(element);
    };

    const installSystemDocs = async () => {
        if (confirm("Install UNITY CORE Manual?")) {
            await addDoc(collection(db, 'artifacts', 'unity-work-os', 'public', 'data', 'archives'), {
                title: "UNITY CORE v3.3 Manual",
                content: SYSTEM_MANUAL,
                category: 'docs',
                type: 'file',
                parentFolderId: 'root',
                teamId: user.teamId,
                createdBy: "System",
                createdAt: serverTimestamp()
            });
            logActivity(`installed System Documentation`, 'ARCHIVE_DOC_ADDED');
            toast.success("Manual Installed!");
        }
    };

    const currentItems = items.filter(i => {
        const isChild = (i.parentFolderId || 'root') === currentFolder;
        const matchesSearch = i.title.toLowerCase().includes(searchTerm.toLowerCase());
        if (searchTerm) return matchesSearch && i.type === 'file';
        return isChild;
    });

    const visibleFolders = currentItems.filter(i => i.type === 'folder');
    const visibleFiles = currentItems.filter(i => i.type !== 'folder');

    const getPlaceholders = () => {
        switch (activeCategory) {
            case 'snippets': return { title: "e.g. AdManager Script", content: "public class..." };
            case 'docs': return { title: "e.g. Game GDD", content: "# Game Details..." };
            case 'links': return { title: "e.g. Asset Pack", content: "https://..." };
            default: return { title: "", content: "" };
        }
    };
    const placeholders = getPlaceholders();

    return (
        <div className="h-full flex flex-col bg-[#0a0a0a] relative overflow-hidden">
            <div className="absolute inset-0 bg-[linear-gradient(to_right,#80808012_1px,transparent_1px),linear-gradient(to_bottom,#80808012_1px,transparent_1px)] bg-[size:24px_24px] pointer-events-none"></div>

            <div className="p-6 border-b border-white/5 flex justify-between items-center relative z-10 bg-[#0a0a0a]/80 backdrop-blur-md">
                <div>
                    <h1 className="text-2xl font-bold text-white flex items-center gap-3">
                        <Database className="text-emerald-500" /> THE ARCHIVES
                    </h1>
                    <p className="text-xs text-gray-500 font-mono mt-1">Knowledge Base & Code Repository</p>
                </div>
                <div className="flex gap-3">
                    <div className="relative">
                        <Search className="absolute left-3 top-2.5 text-gray-500" size={16} />
                        <input type="text" placeholder="Search files..." value={searchTerm} onChange={(e) => setSearchTerm(e.target.value)} className="bg-[#151518] border border-white/10 pl-10 pr-4 py-2 rounded-xl text-sm text-gray-300 focus:border-emerald-500/50 outline-none w-64" />
                    </div>
                    <button onClick={() => setIsFolderModalOpen(true)} className="bg-[#151518] hover:bg-white/5 text-emerald-400 border border-emerald-500/30 px-4 py-2 rounded-xl text-xs font-bold flex items-center gap-2 transition-colors"><FolderPlus size={16} /> New Folder</button>
                    <button onClick={() => setIsAddModalOpen(true)} className="bg-emerald-600 hover:bg-emerald-500 text-white px-4 py-2 rounded-xl text-xs font-bold flex items-center gap-2 shadow-lg shadow-emerald-900/20"><Plus size={16} /> Add File</button>
                </div>
            </div>

            <div className="flex flex-1 overflow-hidden relative z-10">
                <div className="w-64 border-r border-white/5 p-4 space-y-2 bg-[#0f0f12]">
                    {[{ id: 'snippets', label: 'Code Snippets', icon: Code }, { id: 'docs', label: 'Documentation', icon: FileText }, { id: 'links', label: 'Resource Links', icon: LinkIcon }].map(cat => (
                        <button key={cat.id} onClick={() => setActiveCategory(cat.id)} className={`w-full flex items-center gap-3 px-4 py-3 rounded-xl text-sm font-bold transition-all ${activeCategory === cat.id ? 'bg-emerald-500/10 text-emerald-400 border border-emerald-500/20' : 'text-gray-500 hover:bg-white/5 hover:text-gray-300'}`}>
                            <cat.icon size={18} /> {cat.label}
                        </button>
                    ))}
                </div>

                <div className="flex-1 flex flex-col min-h-0">
                    <div className="px-6 py-3 border-b border-white/5 bg-[#0f0f12]/50 flex items-center gap-2 text-sm">
                        {folderPath.map((folder, index) => (
                            <React.Fragment key={folder.id}>
                                <button
                                    onClick={() => navigateBreadcrumb(index)}
                                    className={`hover:text-emerald-400 transition-colors ${index === folderPath.length - 1 ? 'text-white font-bold' : 'text-gray-500'}`}
                                >
                                    {folder.name}
                                </button>
                                {index < folderPath.length - 1 && <ChevronRight size={14} className="text-gray-600" />}
                            </React.Fragment>
                        ))}
                    </div>

                    <div className="flex-1 overflow-y-auto p-6 custom-scrollbar">
                        {visibleFolders.length === 0 && visibleFiles.length === 0 && !searchTerm && (
                            <div className="h-full flex flex-col items-center justify-center text-gray-600 opacity-80">
                                <Folder size={48} className="mb-4 text-gray-700" />
                                <p className="text-sm font-bold">This folder is empty.</p>
                                {currentFolder === 'root' && activeCategory === 'docs' && <button onClick={installSystemDocs} className="mt-6 flex items-center gap-2 px-6 py-3 bg-blue-600/10 text-blue-400 border border-blue-500/30 rounded-xl hover:bg-blue-600/20 transition-all font-bold text-xs"><DownloadCloud size={16} /> Install System Manual</button>}
                            </div>
                        )}

                        {visibleFolders.length > 0 && (
                            <div className="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-5 gap-4 mb-8">
                                {visibleFolders.map(folder => (
                                    <div
                                        key={folder.id}
                                        onClick={() => enterFolder(folder)}
                                        onDragOver={handleDragOver}
                                        onDrop={(e) => handleDrop(e, folder.id)}
                                        className="group bg-[#151518] border border-white/5 p-4 rounded-xl flex flex-col items-center justify-center cursor-pointer hover:bg-[#1a1a1d] hover:border-emerald-500/50 transition-all relative"
                                    >
                                        <Folder size={40} className="text-emerald-500/80 mb-2 group-hover:scale-110 transition-transform" fill="currentColor" fillOpacity={0.2} />
                                        <span className="text-sm text-gray-300 font-bold truncate w-full text-center">{folder.title}</span>
                                        <span className="text-[10px] text-gray-500 font-mono mt-1">{getItemCount(folder.id)} items</span>
                                        <button onClick={(e) => { e.stopPropagation(); handleDelete(folder); }} className="absolute top-2 right-2 text-gray-600 hover:text-red-400 opacity-0 group-hover:opacity-100 transition-opacity"><Trash2 size={12} /></button>
                                    </div>
                                ))}
                            </div>
                        )}

                        <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
                            {visibleFiles.map(item => (
                                <div
                                    key={item.id}
                                    draggable="true"
                                    onDragStart={(e) => handleDragStart(e, item.id)}
                                    className="bg-[#151518] border border-white/5 rounded-2xl p-5 hover:border-emerald-500/30 transition-all group relative overflow-hidden flex flex-col active:cursor-grabbing cursor-grab"
                                >
                                    <div className="flex justify-between items-start mb-3">
                                        <div className="flex items-center gap-3">
                                            <div className="p-2 bg-emerald-500/10 rounded-lg text-emerald-500">
                                                {activeCategory === 'snippets' ? <Code size={18} /> : activeCategory === 'docs' ? <Book size={18} /> : <LinkIcon size={18} />}
                                            </div>
                                            <div>
                                                <h3 className="font-bold text-gray-200 text-sm">{item.title}</h3>
                                                <p className="text-[10px] text-gray-600 font-mono">by {item.createdBy}</p>
                                            </div>
                                        </div>
                                        <div className="flex gap-2">
                                            {currentFolder !== 'root' && (
                                                <button onClick={() => moveItemUp(item)} className="text-gray-600 hover:text-blue-400 opacity-0 group-hover:opacity-100 transition-opacity" title="Move out of folder">
                                                    <CornerUpLeft size={16} />
                                                </button>
                                            )}
                                            <button onClick={() => handleDelete(item)} className="text-gray-600 hover:text-red-400 opacity-0 group-hover:opacity-100 transition-opacity"><Trash2 size={16} /></button>
                                        </div>
                                    </div>

                                    {activeCategory === 'snippets' && (
                                        <div className="relative mt-2 flex-1 group/code">
                                            <pre className="bg-[#0a0a0a] p-3 rounded-lg text-xs text-gray-400 font-mono overflow-x-auto border border-white/5 custom-scrollbar max-h-40"><code>{item.content}</code></pre>
                                            <div className="absolute top-2 right-2 flex gap-1 opacity-0 group-hover/code:opacity-100 transition-opacity">
                                                <button onClick={() => downloadFile(item.title, item.content, 'snippets')} className="p-1.5 bg-white/10 hover:bg-white/20 rounded text-gray-400 hover:text-blue-400 transition-colors"><Download size={14} /></button>
                                                <button onClick={() => copyToClipboard(item.content)} className="p-1.5 bg-white/10 hover:bg-white/20 rounded text-gray-400 hover:text-white transition-colors"><Copy size={14} /></button>
                                            </div>
                                        </div>
                                    )}
                                    {activeCategory === 'docs' && (
                                        <div className="mt-2 relative flex-1">
                                            <div className="text-sm text-gray-400 leading-relaxed whitespace-pre-wrap max-h-40 overflow-y-auto custom-scrollbar pr-2 font-mono bg-black/20 p-3 rounded-lg border border-white/5">{item.content}</div>
                                            <div className="flex gap-2 justify-end mt-3 opacity-0 group-hover:opacity-100 transition-opacity">
                                                <button onClick={() => copyToClipboard(item.content)} className="flex items-center gap-1 text-[10px] bg-white/5 hover:bg-white/10 text-gray-400 hover:text-white px-2 py-1.5 rounded transition-colors"><Copy size={12} /> Copy</button>
                                                <button onClick={() => downloadFile(item.title, item.content, 'docs')} className="flex items-center gap-1 text-[10px] bg-blue-600/20 hover:bg-blue-600/40 text-blue-400 hover:text-white px-2 py-1.5 rounded transition-colors"><Download size={12} /> Download</button>
                                            </div>
                                        </div>
                                    )}
                                    {activeCategory === 'links' && (
                                        <div className="mt-2 flex-1">
                                            <a href={item.content} target="_blank" rel="noreferrer" className="flex items-center gap-2 text-blue-400 hover:text-blue-300 text-xs bg-blue-500/10 p-3 rounded-xl border border-blue-500/20 transition-colors"><ExternalLink size={14} /> {item.content}</a>
                                        </div>
                                    )}
                                </div>
                            ))}
                        </div>
                    </div>
                </div>
            </div>

            {isAddModalOpen && (
                <div className="fixed inset-0 bg-black/80 backdrop-blur-sm z-50 flex items-center justify-center p-4 animate-fade-in">
                    <div className="bg-[#151518] border border-white/10 w-full max-w-lg rounded-2xl shadow-2xl flex flex-col">
                        <div className="p-5 border-b border-white/5 flex justify-between items-center">
                            <h2 className="text-white font-bold">Add {activeCategory}</h2>
                            <button onClick={() => setIsAddModalOpen(false)}><X size={20} className="text-gray-500 hover:text-white" /></button>
                        </div>
                        <div className="p-6 space-y-4">
                            <input className="w-full bg-[#0a0a0a] border border-white/10 p-3 rounded-xl text-sm text-white focus:border-emerald-500 outline-none" placeholder={placeholders.title} value={newItem.title} onChange={e => setNewItem({ ...newItem, title: e.target.value })} />
                            {activeCategory === 'links' ? (
                                <input className="w-full bg-[#0a0a0a] border border-white/10 p-3 rounded-xl text-sm text-blue-400 focus:border-emerald-500 outline-none" placeholder={placeholders.content} value={newItem.content} onChange={e => setNewItem({ ...newItem, content: e.target.value })} />
                            ) : (
                                <textarea rows={12} className="w-full bg-[#0a0a0a] border border-white/10 p-3 rounded-xl text-sm text-gray-300 font-mono focus:border-emerald-500 outline-none resize-none" placeholder={placeholders.content} value={newItem.content} onChange={e => setNewItem({ ...newItem, content: e.target.value })} />
                            )}
                        </div>
                        <div className="p-5 border-t border-white/5 flex justify-end gap-3">
                            <button onClick={handleSaveFile} disabled={isSavingFile} className="bg-emerald-600 hover:bg-emerald-500 disabled:opacity-50 text-white px-6 py-2 rounded-xl text-sm font-bold flex items-center gap-2">
                                {isSavingFile ? <Loader size={16} className="animate-spin" /> : <Save size={16} />}
                                {isSavingFile ? 'Saving...' : 'Save'}
                            </button>
                        </div>
                    </div>
                </div>
            )}

            {isFolderModalOpen && (
                <div className="fixed inset-0 bg-black/80 backdrop-blur-sm z-50 flex items-center justify-center p-4 animate-fade-in">
                    <div className="bg-[#151518] border border-white/10 w-full max-w-sm rounded-2xl shadow-2xl flex flex-col">
                        <div className="p-5 border-b border-white/5 flex justify-between items-center">
                            <h2 className="text-white font-bold flex items-center gap-2"><FolderPlus size={18} className="text-emerald-500" /> New Folder</h2>
                            <button onClick={() => setIsFolderModalOpen(false)}><X size={20} className="text-gray-500 hover:text-white" /></button>
                        </div>
                        <div className="p-6">
                            <input className="w-full bg-[#0a0a0a] border border-white/10 p-3 rounded-xl text-sm text-white focus:border-emerald-500 outline-none" placeholder="Folder Name (e.g. Ads)" value={newFolderName} onChange={e => setNewFolderName(e.target.value)} />
                        </div>
                        <div className="p-5 border-t border-white/5 flex justify-end gap-3">
                            <button
                                onClick={handleCreateFolder}
                                disabled={isCreatingFolder}
                                className="bg-emerald-600 hover:bg-emerald-500 disabled:opacity-50 text-white px-6 py-2 rounded-xl text-sm font-bold flex items-center gap-2"
                            >
                                {isCreatingFolder ? <Loader size={16} className="animate-spin" /> : null}
                                {isCreatingFolder ? 'Creating...' : 'Create Folder'}
                            </button>
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
};

export default ArchivesView;